version: '3.8'                 # Compose file format v3.8 :contentReference[oaicite:0]{index=0}
services:
  db:
    image: postgres:15         # Official PostgreSQL image :contentReference[oaicite:1]{index=1}
    restart: always
    environment:
      POSTGRES_DB: shortenurl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .                   # Builds from Dockerfile in project root :contentReference[oaicite:2]{index=2}
    image: shortenurl:latest
    depends_on:
      - db                     # Ensures db starts before app :contentReference[oaicite:3]{index=3}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shortenurl
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: